/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Seba-PC
 */
public class Principal extends javax.swing.JFrame {

    public static String cargo;

    public Principal(String cargo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.cargo = cargo;
    }

    private Principal() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuCerrarSesion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        nuevoProyecto = new javax.swing.JMenuItem();
        jMenuAddMaterial = new javax.swing.JMenu();
        agregarMaterial = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        nuevoGasto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        VerInformes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/construbaelogo3.png"))); // NOI18N
        jLabel1.setToolTipText("");

        VentanaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE))
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/open-menu (1).png"))); // NOI18N
        jMenu6.setText("Menu");
        jMenu6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuCerrarSesion.setText("Cerrar Sesion");
        jMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCerrarSesion);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/real-estate.png"))); // NOI18N
        jMenu1.setText("Proyecto");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nuevoProyecto.setText("Nuevo Proyecto");
        nuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProyectoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoProyecto);

        jMenuBar1.add(jMenu1);

        jMenuAddMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/inventory.png"))); // NOI18N
        jMenuAddMaterial.setText("Inventario");
        jMenuAddMaterial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        agregarMaterial.setText("Ver Inventario");
        agregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMaterialActionPerformed(evt);
            }
        });
        jMenuAddMaterial.add(agregarMaterial);

        jMenuItem2.setText("Agregar Material");
        jMenuAddMaterial.add(jMenuItem2);

        jMenuBar1.add(jMenuAddMaterial);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/money.png"))); // NOI18N
        jMenu3.setText("Gasto");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nuevoGasto.setText("Nuevo Gasto");
        nuevoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoGastoActionPerformed(evt);
            }
        });
        jMenu3.add(nuevoGasto);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/constructor.png"))); // NOI18N
        jMenu4.setText("Personal");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem4.setText("Agregar Personal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem3.setText("Pagar Sueldos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/informes.png"))); // NOI18N
        jMenu5.setText("Informes");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        VerInformes.setText("Ver Gastos Generales");
        VerInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInformesActionPerformed(evt);
            }
        });
        jMenu5.add(VerInformes);

        jMenuItem1.setText("Ver Gastos Proyecto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProyectoActionPerformed
        ProyectosForm pf = new ProyectosForm();
        VentanaPrincipal.add(pf);
        pf.setVisible(true);

    }//GEN-LAST:event_nuevoProyectoActionPerformed

    private void agregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMaterialActionPerformed
        InventarioForm inv = new InventarioForm();
        VentanaPrincipal.add(inv);
        inv.setVisible(true);
    }//GEN-LAST:event_agregarMaterialActionPerformed

    private void VerInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInformesActionPerformed
        if (this.cargo.equals("admin")) {
            InformeForm inform = new InformeForm();
            VentanaPrincipal.add(inform);
            inform.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita Permisos de Administrador para acceder a esta pestaña");
        }


    }//GEN-LAST:event_VerInformesActionPerformed

    private void nuevoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoGastoActionPerformed

        if (this.cargo.equals("admin")) {
            GastosForm gf = new GastosForm();
            VentanaPrincipal.add(gf);
            gf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita Permisos de Administrador para acceder a esta pestaña");
        }

    }//GEN-LAST:event_nuevoGastoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (this.cargo.equals("admin")) {
            GastosProyectosForm gpf = new GastosProyectosForm();
            VentanaPrincipal.add(gpf);
            gpf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita Permisos de Administrador para acceder a esta pestaña");
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionActionPerformed
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        
    }//GEN-LAST:event_jMenuCerrarSesionActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
         if (this.cargo.equals("admin")) {
            PersonalForm pform = new PersonalForm();
            VentanaPrincipal.add(pform);
            pform.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita Permisos de Administrador para acceder a esta pestaña");
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (this.cargo.equals("admin")) {
            SueldosForm sform = new SueldosForm();
            VentanaPrincipal.add(sform);
            sform.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita Permisos de Administrador para acceder a esta pestaña");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenuItem VerInformes;
    private javax.swing.JMenuItem agregarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuAddMaterial;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCerrarSesion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem nuevoGasto;
    private javax.swing.JMenuItem nuevoProyecto;
    // End of variables declaration//GEN-END:variables
}
