/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GastoDAO;
import Controlador.PersonalDAO;
import Modelo.Personal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seba-PC
 */
public class SueldosForm extends javax.swing.JInternalFrame {

    PersonalDAO pdao = new PersonalDAO();
    GastoDAO gdao = new GastoDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    public SueldosForm() {
        initComponents();
        listarPersonal();
    }

    void listarPersonal() {
        modelo = (DefaultTableModel) jTable1.getModel();
        List<Personal> lista = pdao.listarInventario();
        Object[] object = new Object[3];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getNombre();
            object[1] = lista.get(i).getCargo();
            object[2] = lista.get(i).getSueldo();
            modelo.addRow(object);
        }
        jTable1.setModel(modelo);

    }

    void LimpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        payAll = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pago de Sueldos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cargo", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Personal:");

        payAll.setText("Pagar");
        payAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payAllActionPerformed(evt);
            }
        });

        pay.setText("Pagar");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jLabel1.setText("Pagar persona seleccionada:");

        jLabel3.setText("Pagar todos los sueldos:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Personal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pay)
                                .addGap(81, 81, 81)
                                .addComponent(jButton2)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payAll)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payAll)
                    .addComponent(pay)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        modelo = (DefaultTableModel) jTable1.getModel();
        String nom = (String) modelo.getValueAt(jTable1.getSelectedRow(), 0);
        String cargo = (String) modelo.getValueAt(jTable1.getSelectedRow(), 1);
        int sueldo = (int) modelo.getValueAt(jTable1.getSelectedRow(), 2);

        int respuesta = JOptionPane.showConfirmDialog(this, "Desea pagar sueldo de : " + nom + " ---- " + cargo + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            gdao.nuevoGasto("Sueldo", nom + " " + cargo, sueldo, 1, sueldo, fecha());
            JOptionPane.showMessageDialog(null, "Pago ingresado con exito");
        } else {
            System.out.println("no acepto");
        }


    }//GEN-LAST:event_payActionPerformed

    private void payAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payAllActionPerformed
        modelo = (DefaultTableModel) jTable1.getModel();
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea pagar todos los sueldos?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String nom = (String) modelo.getValueAt(i, 0);
                String cargo = (String) modelo.getValueAt(i, 1);
                int sueldo = (int) modelo.getValueAt(i, 2);
                gdao.nuevoGasto("Sueldo", nom + " " + cargo, sueldo, 1, sueldo, fecha());
            }
            JOptionPane.showMessageDialog(null, "Pago ingresado con exito");
        } else {
            System.out.println("no acepto");
        }
    }//GEN-LAST:event_payAllActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        LimpiarTabla();
        listarPersonal();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modelo = (DefaultTableModel) jTable1.getModel();
        String nom = (String) modelo.getValueAt(jTable1.getSelectedRow(), 0);
        String carac = (String) modelo.getValueAt(jTable1.getSelectedRow(), 1);

        int respuesta = JOptionPane.showConfirmDialog(this, "Desea borrar a: " + nom + " de la lista de empleados?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            pdao.delete(nom, carac);
            LimpiarTabla();
            btnActualizarActionPerformed(evt);
            JOptionPane.showMessageDialog(null, "Empleado eliminado con exito.");
        } else {
            System.out.println("no acepto");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private String fecha() {

        Date calendario = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");

        String FechaCorrecta = sdf.format(calendario);

        return FechaCorrecta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pay;
    private javax.swing.JButton payAll;
    // End of variables declaration//GEN-END:variables
}
